FROM golang:1.24 AS builder

WORKDIR /opt/app/

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o project .

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /opt/app/project /app/project
COPY static static
COPY templates templates

ENTRYPOINT [ "/app/project" ]